### PR TITLE
fix: Fall back to more generic languages for selection box default

### LINKED ISSUE #289: Language selector does not match language when default is not English
my page is in german although I selected english from the drop down menu
2020-04-27_17h16_56

### PR DESCRIPTION
**Pull request by mikebryant**
Try to fall back gracefully, using the list of fallback languages in the i18next list

Fixes #289

### CODE REVIEW

File: js/translations.js [hunk 1]
```diff
@@ -3,6 +3,23 @@ function updateContent() {
...
+  'hu': 'magyar',
+  'it': 'Italiano',
+  'ja': '日本語',
+  'ko': '한국어',
+  'nl': 'Nederlands',
+  'pt-BR': 'Português',
+  'ru': 'Русский',
+  'zh-CN': '简体中文',
+  'zh-TW': '繁體中文',
+  'th-TH': 'ไทย',
```
Comment (DevSplash) [inline js/translations.js:21]:
```suggestion
  'es': 'Español',
  'fr': 'Français',
  'hu': 'magyar',
  'it': 'Italiano',
  'ja': '日本語',
  'ko': '한국어',
  'nl': 'Nederlands',
  'pt-BR': 'Português',
  'ru': 'Русский',
  'th': 'ไทย',
  'zh-CN': '简体中文',
  'zh-TW': '繁體中文'
```
If the browser locale is set to `es`, `locales/es.json` will be loaded, but the selector will select `en`. Make sure that language codes and file names are consistent.
