### PR TITLE
fix: Decrease precision for tiny numbers

### LINKED ISSUE #216: What a surprise! I see "e" in the site
Excuse me, I'm not good at English.

Look at this link. [https://turnipprophet.io/?prices=107.96.91.86.81........&pattern=3](https://turnipprophet.io/?prices=107.96.91.86.81........&pattern=3)

"Fluctuating" is "2.39e-7%" ! as 0% ?

### PR DESCRIPTION
**Pull request by mikebryant**
When the numbers are so small then end up in e notation is pushes
everything too far to the right. Give up when it's too small to be
really useful.

Fixes #216

### CODE REVIEW

File: js/scripts.js [hunk 1]
```diff
@@ -259,6 +259,21 @@ const getPriceClass = function(buy_price, max) {
   return "";
 }
 
+const displayPercentage = function(fraction) {
+  if (Number.isFinite(fraction)) {
+    let percent = fraction * 100;
+    if (percent >= 1) {
+      return percent.toPrecision(3) + '%';
+    } else if (percent > 0.01) {
```
Comment (peter50216) [inline js/scripts.js:267]: Should this be 0.1?

Comment (theRTC204) [reply js/scripts.js:267]: 0.01 seems right to me. We want anything less than. 1, but greater than 0.01 to appear as itt's actual percentage value.

That being said, now that I look at it, we probably want `>=` instead of `>`.

Comment (peter50216) [reply js/scripts.js:267]: Then should the "else" part be "<0.01%"? Or it might be weird that both "0.02%" and "<0.1%" can appear.

Comment (theRTC204) [reply js/scripts.js:267]: Oh I didn't even catch that. I assume the else was meant to be `<0.01%`

Comment (mikebryant) [reply js/scripts.js]: Good catch, thanks. Fixed :)
